-- curated list of the themes i like
-- they can be applied in the main file
return {
    fideloper = 'Fideloper',
    _3024_base16 = '3024 (base16)',
    _3024_night = '3024 Night',
    catpuccin_frappe = 'Catppuccin Frappe',
    abernathy = 'Abernathy',
    aci_gogh = 'Aci (Gogh)',
    adventure = 'Adventure',
    adventure_time_gogh = 'Adventure Time (Gogh)',
    afterglow = 'Afterglow',
    alien_blood_gogh = 'Alien Blood (Gogh)',
    andromeda = 'Andromeda',
    apple_system_colors = 'Apple System Colors',
    arcoiris = 'arcoiris',
    argonaut = 'Argonaut',
    astromouse_terminal_sexy = 'astromouse (terminal.sexy)',
    atelier_forest_base_16 = 'Atelier Forest (base16)',
    banana_blueberry = 'Banana Blueberry',
    belge_terminal_sexy = 'Belge (terminal.sexy)',
    blue_matrix = 'Blue Matrix',
    breath_gogh = 'Breath (Gogh)',
    breath_darker_gogh = 'Breath Darker (Gogh)',
    brewer_base16 = 'Brewer (base16)',
    brewer_dark_terminal_sexy = 'Brewer (dark) (terminal.sexy)',
    bright_base16 = 'Bright (base16)',
    bright_lights = 'Bright Lights',
    brogrammer = 'Brogrammer',
    builtin_dark = 'Builtin Dark',
    builtin_tango_dark = 'Builtin Tango Dark',
    campbell_gogh = 'Campbell (Gogh)',
    catpuccin_mocha = 'Catppuccin Mocha',
    cga = 'CGA',
    cloud_terminal_sexy = 'Cloud (terminal.sexy)',
    color_star_terminal_sexy = 'Color Star (terminal.sexy)',
    dark_pastel = 'Dark Pastel',
    dark_violet_base16 = 'Dark Violet (base16)',
    dark_moss = 'darkmoss (base16)',
    derp_terminal_sexy = 'Derp (terminal.sexy)',
    dracula = 'Dracula',
    duckbones = 'duckbones',
    windows10_base16 = 'Windows 10 (base16)',
}
